import { createContext, useContext, useState } from 'react'

const translations = {
  tr: {
    // Navbar
    nav_home: 'Ana Sayfa',
    nav_analyze: 'Analizi Başlat',
    nav_login: 'Giriş Yap',

    // HomePage
    hero_badge: 'Architecture Visualizer',
    hero_title_1: 'Kodunuzun Mimarisi',
    hero_title_2: 'Anında Ortaya Çıksın',
    hero_desc: 'ZIP yükle, Tree-sitter analiz etsin. Python, JavaScript ve TypeScript projelerinizden otomatik olarak Mermaid diyagramları ve Gemini AI destekli mimari özetler oluşturun.',
    hero_btn_start: 'Analizi Başlat',
    hero_btn_more: 'Daha Fazla Bilgi',
    stat_lang: 'Desteklenen Dil',
    stat_zip: 'Maksimum ZIP',
    stat_ai: 'Mimari Özet',
    features_title: 'Özellikler',
    features_subtitle: 'CodeAtlas, kod analizini kolaylaştırır',
    feature1_title: 'Tree-sitter Analizi',
    feature1_desc: 'Python, JavaScript ve TypeScript dosyalarını yapısal olarak analiz eder. Sembolleri, importları ve kod yapısını çıkarır.',
    feature2_title: 'Mermaid Diyagramları',
    feature2_desc: 'Analiz sonuçlarından otomatik olarak mimari diyagramlar oluşturur. UML bileşen diyagramı formatında sunar.',
    feature3_title: 'Gemini AI Özeti',
    feature3_desc: 'Gemini AI destekli mimari özet ile kod tabanınızın yüksek seviyeli açıklamasını alın.',
    feature4_title: 'Dosya Ağacı',
    feature4_desc: 'Projenizin komple dosya yapısını görüntüleyin. Her dosyanın sembollerini ve import ilişkilerini keşfedin.',
    how_title: 'Nasıl Çalışır',
    how_subtitle: 'Üç basit adımda projenizi analiz edin',
    step1_title: 'ZIP Yükle',
    step1_desc: 'Analiz etmek istediğiniz projenin ZIP dosyasını yükleyin.',
    step2_title: 'Analiz Et',
    step2_desc: 'Tree-sitter kodunuzu otomatik olarak analiz eder ve yapısını çıkarır.',
    step3_title: 'Mimariyi Gör',
    step3_desc: 'Mermaid diyagramı ve Gemini özeti ile projenizin mimarisini keşfedin.',
    langs_title: 'Desteklenen Diller',
    langs_subtitle: 'Şu anda aşağıdaki dillerde analiz desteği mevcut',
    cta_title: 'Projenizin Mimarisini Keşfedin',
    cta_desc: 'Hemen bir ZIP dosyası yükleyin ve kod tabanınızın nasıl göründüğünü görün.',
    cta_btn: 'Analizi Başlat',
    footer_text: 'Kod mimarisi görselleştirme aracı',
    visual_project: 'Proje',

    // AnalysisPage
    analysis_eyebrow: 'CodeAtlas',
    analysis_hero_title: 'Zip yükle, mimariyi Mermaid diyagramına dönüştür.',
    analysis_lead: 'Backend zip içindeki Python ve JS/TS dosyalarını Tree-sitter ile analiz eder, seçtiğin LLM sağlayıcısı varsa mimari özet ve diyagramı zenginleştirir.',
    analysis_file_select: 'Proje zip dosyası seç',
    analysis_file_hint: 'Desteklenen diller: Python, JavaScript, TypeScript. Varsayılan zip limiti: 100 MB.',
    analysis_provider_label: 'Analiz sağlayıcısı',
    provider_gemini_desc: 'Google Gemini ile hızlı mimari özet ve diyagram üretimi.',
    provider_gpt_desc: 'OpenAI GPT-4o mini ile alternatif mimari analiz.',
    analysis_nlp_label: 'NLP ile dosya seçimini kullan',
    analysis_nlp_hint: 'Kapalıyken LLM prompt\'una tüm Tree-sitter analizi gönderilir; daha detaylı ama daha uzun sürebilir.',
    analysis_submit: 'Analizi Başlat',
    analysis_loading: 'Analiz ediliyor...',
    analysis_error_no_file: 'Lütfen analiz edilecek .zip dosyasını seçin.',
    analysis_error_generic: 'Beklenmeyen bir hata oluştu.',
    analysis_error_fail: 'Analiz isteği başarısız oldu.',
    diagram_title: 'Mermaid Diyagramı',
    diagram_desc: 'Gruplar klasör/bileşen sınırlarını, kesik çizgiler dosyalar arası bağımlılıkları gösterir.',
    diagram_reset: 'Sıfırla',
    diagram_fit: 'Sığdır',
    diagram_node_colors: 'Düğüm renkleri',
    diagram_edge_title: 'Çizgi anlamı',
    legend_project_title: 'Proje',
    legend_project_desc: 'Analiz edilen zip/proje kökü.',
    legend_directory_title: 'Mimari katman',
    legend_directory_desc: 'Aynı klasördeki dosyaları gruplayan bileşen alanı.',
    legend_file_title: 'Dosya / bileşen',
    legend_file_desc: 'Diyagramda görünen önemli kaynak dosyalar.',
    legend_symbol_title: 'Fonksiyon / class',
    legend_symbol_desc: 'Dosyanın içindeki seçilmiş önemli semboller.',
    edge_solid: 'düz çizgi',
    edge_solid_desc: 'Proje, katman, dosya ve sembol hiyerarşisini gösterir.',
    edge_dashed: 'kesik çizgi',
    edge_dashed_desc: 'Dosyalar arasındaki import veya bağımlılık ilişkisini gösterir.',
    filetree_title: 'Dosya Ağacı',
    components_title: 'Bileşen Açıklamaları',
    symbols_title: 'Tree-sitter Sembolleri',
    symbol_line: 'satır',
    mermaid_error: 'Mermaid diyagramı render edilemedi.',

    // LoginPage
    login_title: 'Tekrar Hoşgeldiniz',
    login_subtitle: 'Sistem mimarinizi anında görselleştirin',
    login_name_placeholder: 'Kullanıcı Adı',
    login_password_placeholder: 'Şifre',
    login_submit: 'Giriş Yap',
    login_loading: 'Giriş yapılıyor...',
    login_or: 'veya',
    login_github: 'GitHub ile devam et',
    login_no_account: 'Hesabınız yok mu?',
    login_signup: 'Kayıt Ol',

    // RegisterPage
    register_title: 'Hesap Oluştur',
    register_subtitle: 'Sistem mimarinizi anında görselleştirin',
    register_fullname: 'Ad Soyad',
    register_email: 'E-posta Adresi',
    register_password: 'Şifre',
    register_confirm: 'Şifreyi Onayla',
    register_submit: 'Kayıt Ol',
    register_loading: 'Hesap oluşturuluyor...',
    register_or: 'veya',
    register_github: 'GitHub ile devam et',
    register_has_account: 'Zaten hesabınız var mı?',
    register_login: 'Giriş Yap',
    register_password_mismatch: 'Şifreler eşleşmiyor!',
  },

  en: {
    // Navbar
    nav_home: 'Home',
    nav_analyze: 'Start Analysis',
    nav_login: 'Login',

    // HomePage
    hero_badge: 'Architecture Visualizer',
    hero_title_1: 'Your Code Architecture',
    hero_title_2: 'Revealed Instantly',
    hero_desc: 'Upload a ZIP, let Tree-sitter analyze it. Automatically generate Mermaid diagrams and Gemini AI-powered architecture summaries from your Python, JavaScript, and TypeScript projects.',
    hero_btn_start: 'Start Analysis',
    hero_btn_more: 'Learn More',
    stat_lang: 'Supported Languages',
    stat_zip: 'Max ZIP Size',
    stat_ai: 'Architecture Summary',
    features_title: 'Features',
    features_subtitle: 'CodeAtlas makes code analysis easy',
    feature1_title: 'Tree-sitter Analysis',
    feature1_desc: 'Structurally analyzes Python, JavaScript, and TypeScript files. Extracts symbols, imports, and code structure.',
    feature2_title: 'Mermaid Diagrams',
    feature2_desc: 'Automatically generates architecture diagrams from analysis results. Presented in UML component diagram format.',
    feature3_title: 'Gemini AI Summary',
    feature3_desc: 'Get a high-level description of your codebase with Gemini AI-powered architecture summaries.',
    feature4_title: 'File Tree',
    feature4_desc: 'View the complete file structure of your project. Discover symbols and import relationships for each file.',
    how_title: 'How It Works',
    how_subtitle: 'Analyze your project in three simple steps',
    step1_title: 'Upload ZIP',
    step1_desc: 'Upload the ZIP file of the project you want to analyze.',
    step2_title: 'Analyze',
    step2_desc: 'Tree-sitter automatically analyzes your code and extracts its structure.',
    step3_title: 'See Architecture',
    step3_desc: 'Explore your project\'s architecture with a Mermaid diagram and Gemini summary.',
    langs_title: 'Supported Languages',
    langs_subtitle: 'Analysis is currently available for the following languages',
    cta_title: 'Explore Your Project\'s Architecture',
    cta_desc: 'Upload a ZIP file now and see what your codebase looks like.',
    cta_btn: 'Start Analysis',
    footer_text: 'Code architecture visualization tool',
    visual_project: 'Project',

    // AnalysisPage
    analysis_eyebrow: 'CodeAtlas',
    analysis_hero_title: 'Upload a zip, convert architecture to a Mermaid diagram.',
    analysis_lead: 'The backend analyzes Python and JS/TS files in the zip with Tree-sitter, and enriches the architecture summary and diagram with your chosen LLM provider if available.',
    analysis_file_select: 'Select project zip file',
    analysis_file_hint: 'Supported languages: Python, JavaScript, TypeScript. Default zip limit: 100 MB.',
    analysis_provider_label: 'Analysis provider',
    provider_gemini_desc: 'Fast architecture summary and diagram generation with Google Gemini.',
    provider_gpt_desc: 'Alternative architecture analysis with OpenAI GPT-4o mini.',
    analysis_nlp_label: 'Use NLP for file selection',
    analysis_nlp_hint: 'When disabled, the full Tree-sitter analysis is sent to the LLM prompt; more detailed but may take longer.',
    analysis_submit: 'Start Analysis',
    analysis_loading: 'Analyzing...',
    analysis_error_no_file: 'Please select a .zip file to analyze.',
    analysis_error_generic: 'An unexpected error occurred.',
    analysis_error_fail: 'Analysis request failed.',
    diagram_title: 'Mermaid Diagram',
    diagram_desc: 'Groups show folder/component boundaries, dashed lines show inter-file dependencies.',
    diagram_reset: 'Reset Zoom',
    diagram_fit: 'Fit View',
    diagram_node_colors: 'Node colors',
    diagram_edge_title: 'Edge meaning',
    legend_project_title: 'Project',
    legend_project_desc: 'The analyzed zip/project root.',
    legend_directory_title: 'Architecture layer',
    legend_directory_desc: 'Component area grouping files in the same folder.',
    legend_file_title: 'File / component',
    legend_file_desc: 'Important source files visible in the diagram.',
    legend_symbol_title: 'Function / class',
    legend_symbol_desc: 'Selected important symbols inside a file.',
    edge_solid: 'solid line',
    edge_solid_desc: 'Shows project, layer, file, and symbol hierarchy.',
    edge_dashed: 'dashed line',
    edge_dashed_desc: 'Shows import or dependency relationships between files.',
    filetree_title: 'File Tree',
    components_title: 'Component Descriptions',
    symbols_title: 'Tree-sitter Symbols',
    symbol_line: 'line',
    mermaid_error: 'Could not render the Mermaid diagram.',

    // LoginPage
    login_title: 'Welcome Back',
    login_subtitle: 'Visualize your system architecture instantly',
    login_name_placeholder: 'Username',
    login_password_placeholder: 'Password',
    login_submit: 'Login',
    login_loading: 'Logging in...',
    login_or: 'or',
    login_github: 'Continue with GitHub',
    login_no_account: "Don't have an account?",
    login_signup: 'Sign Up',

    // RegisterPage
    register_title: 'Create Account',
    register_subtitle: 'Visualize your system architecture instantly',
    register_fullname: 'Full Name',
    register_email: 'Email Address',
    register_password: 'Password',
    register_confirm: 'Confirm Password',
    register_submit: 'Sign Up',
    register_loading: 'Creating Account...',
    register_or: 'or',
    register_github: 'Continue with GitHub',
    register_has_account: 'Already have an account?',
    register_login: 'Login',
    register_password_mismatch: 'Passwords do not match!',
  },
}

const LanguageContext = createContext(null)

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('tr')

  const t = (key) => translations[lang]?.[key] ?? key

  const toggleLang = () => setLang((prev) => (prev === 'tr' ? 'en' : 'tr'))

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLang() {
  return useContext(LanguageContext)
}
